language: node_js
node_js:
  - "8"

script:
  - npm run test
  - npm run build

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: add-vuejs-base # should be master after getting the repo together
