language: node_js
node_js:
  - "8"

sudo: required
addons:
  chrome: stable

install:
  - yarn install

script:
  - yarn test
  - yarn build

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master
